### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by assemblu** [dizcza/LCD_ILI9341_TouchScreen#1]
Hi,

Font size doesn't seem to make any changes. Do you know why? I opened the project in CubeIDE. 

`  	LCD_SetTextSize(80);
  		LCD_SetCursor(0, 60);
  		LCD_Printf("TEST\n");`

Thank you.

**Comment by dizcza** [comment]
Hello,
I've never changed the font size in my tests. I do set it to `3` in the main function but I've not played with this parameter.
I'll have a look tomorrow.

**Comment by assemblu** [comment]
> 
> 
> Hello,
> I've never changed the font size in my tests. I do set it to `3` in the main function but I've not played with this parameter.
> I'll have a look tomorrow.

Thank you. I am looking forward to it because I couldn't figure it out on my own so far.
Have a nice day.

**Comment by dizcza** [comment]
The issue lies in unintuitive API (disclaimer: I'm not the author of `lcd.h` drawing lib; I'm the author of `lcd_touch.h` touchscreen lib that is built on top of `lcd.h`).

`LCD_SetTextSize` sets the font id (0-4), and `LCD_SetTextScaled`, if set to `1`, doubles the text size. Therefore, there is a limited number of text scales/sizes (5 * 2 = 10) you can choose from.

I put the comment in main.c:
```c
	LCD_SetTextSize(1);  // Font12
	LCD_SetTextScaled(0);  // don't scale the text size by 2
```

Also, I've updated the F446 CubeIDE lib to the latest version.
Freshly new, give it a try.

**Comment by assemblu** [comment]
I haven't been able to get on GitHub due to my busy schedule. Thank you very much for the solution.
